NIFTY_50 = {
    "RELIANCE.NS": "Reliance Industries",
    "TCS.NS": "Tata Consultancy Services",
    "HDFCBANK.NS": "HDFC Bank",
    "ICICIBANK.NS": "ICICI Bank",
    "INFY.NS": "Infosys",
    "BHARTIARTL.NS": "Bharti Airtel",
    "ITC.NS": "ITC",
    "SBIN.NS": "State Bank of India",
    "LT.NS": "Larsen & Toubro",
    "KOTAKBANK.NS": "Kotak Mahindra Bank",
    "AXISBANK.NS": "Axis Bank",
    "HINDUNILVR.NS": "Hindustan Unilever",
    "BAJFINANCE.NS": "Bajaj Finance",
    "MARUTI.NS": "Maruti Suzuki",
    "ASIANPAINT.NS": "Asian Paints",
    "SUNPHARMA.NS": "Sun Pharmaceutical",
    "TITAN.NS": "Titan Company",
    "ULTRACEMCO.NS": "UltraTech Cement",
    "WIPRO.NS": "Wipro",
    "ONGC.NS": "Oil & Natural Gas Corp",
    "NTPC.NS": "NTPC",
    "ADANIENT.NS": "Adani Enterprises",
    "ADANIPORTS.NS": "Adani Ports",
    "POWERGRID.NS": "Power Grid Corp",
    "M&M.NS": "Mahindra & Mahindra",
    "TATAMOTORS.NS": "Tata Motors",
    "TATASTEEL.NS": "Tata Steel",
    "JSWSTEEL.NS": "JSW Steel",
    "HCLTECH.NS": "HCL Technologies",
    "TECHM.NS": "Tech Mahindra",
    "BAJAJFINSV.NS": "Bajaj Finserv",
    "NESTLEIND.NS": "Nestle India",
    "GRASIM.NS": "Grasim Industries",
    "HINDALCO.NS": "Hindalco Industries",
    "DRREDDY.NS": "Dr. Reddy's Labs",
    "CIPLA.NS": "Cipla",
    "EICHERMOT.NS": "Eicher Motors",
    "BRITANNIA.NS": "Britannia Industries",
    "DIVISLAB.NS": "Divi's Laboratories",
    "BPCL.NS": "Bharat Petroleum",
    "COALINDIA.NS": "Coal India",
    "INDUSINDBK.NS": "IndusInd Bank",
    "SBILIFE.NS": "SBI Life Insurance",
    "HDFCLIFE.NS": "HDFC Life Insurance",
    "BAJAJ-AUTO.NS": "Bajaj Auto",
    "APOLLOHOSP.NS": "Apollo Hospitals",
    "TATACONSUM.NS": "Tata Consumer Products",
    "LTIM.NS": "LTIMindtree",
    "UPL.NS": "UPL",
    "SHRIRAMFIN.NS": "Shriram Finance",
}


def get_all_symbols():
    return list(NIFTY_50.keys())
